# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
selene = "Kampfkarren/selene@0.21.1"   # Lua linter
wally = "UpliftGames/wally@0.3.1"      # Package manager
stylua = "JohnnyMorganz/StyLua@0.15.1" # Stylizer